Use GCC 8, 10, 11, clang 15, bump AFL remove honggfuzz
* gcc-9 is no longer available in Debian testing
* bump AFL fuzzer to latest version
* remove honggfuzz as it doesn't build currently due to:

  linux/unwind.c:27:10: fatal error: libunwind-ptrace.h: No such file or directory
    27 | #include <libunwind-ptrace.h>

Signed-off-by: Petr Štetiar <ynezz@true.cz>