pre-build: fix CI black breakage by pinning it to 19.3b0
Black seems to have dependencies on musl-dev and gcc past 19.3b0
version.  Hopefully this is just temporary. If we wanted to continue
using the latest versions, we could instead add something like `apk add
musl-dev gcc` but this increases the duration of the process
significantly.

Fixes following CI check failure[1]:

 $ make ci-py-checks -f Makefile.ci
  python3 -m venv /builds/openwrtorg/gitlab-evaluation/.venv/openwrt-ci
  ...
  /.venv/openwrt-ci/bin/pip3 install black flake8
  ...
  Installing collected packages: regex, click, attrs, appdirs, toml, typed-ast, pathspec, black, pycodestyle, mccabe, entrypoints, pyflakes, flake8
    Running setup.py install for regex: started
    Running setup.py install for regex: finished with status 'error'
    ...
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/builds/openwrtorg/gitlab-evaluation/.venv/openwrt-ci/include -I/usr/include/python3.7m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.7/regex_3/_regex.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1

1. https://gitlab.com/ynezz/openwrt-gitlab-evaluation/-/jobs/326228113

Ref: https://github.com/psf/black/issues/1112
Signed-off-by: Petr Štetiar <ynezz@true.cz>